### ISSUE TITLE
Errors with couchbase 4.6.1

### ISSUE THREAD

**Issue by jackpf** [TeamWanari/couchbase-query-executor#4]
Hi,

I'm getting some issues with couchbase 4.6.1, notably the sum() and count() methods return this error:

> Unable to execute query due to the following n1ql errors: {"msg":"Expression must be a group key or aggregate: (meta(`subscriptions`).`id`)","code":4210}

Removing this select statement:
`meta(" + bucketName + ").id AS id`
Seems to fix it. Is this a safe fix?

Cheers

**Comment by aBnormaLz** [comment]
Actually that line is needed to get the id of the document, so if you don't need the id further more, that could be a quick-and-dirty solution (but most of the use-cases we need that line :) )

Can you give us some more information like what filters you add to the query, how the built query string looks like, etc. ?

**Comment by jackpf** [comment]
Yeah its currently working for me, as I dont need the ID but guess its still a problem.

An example of a generated query:
`SELECT count(*) as count, meta(`subscriptions`).id AS id  FROM `subscriptions` WHERE firstName = $firstName AND meta(`subscriptions`).id NOT LIKE "_sync:%"`

Returns the error in CB 4.6.1:
`[
  {
    "code": 4210,
    "msg": "Expression must be a group key or aggregate: (meta(`subscriptions`).`id`)",
    "query_from_user": "SELECT count(*) as count, meta(`subscriptions`).id AS id  FROM `subscriptions` WHERE firstName = 'Jack' AND meta(`subscriptions`).id NOT LIKE \"_sync:%\""
  }
]`

It's just generated using the findAll() method with a simple equals filter. The main query runs fine but the count() query returns this error.

**Comment by jackpf** [comment]
Im still pretty new to N1QL queries, but it appears that grouping by ID fixes the problem, like so:

`SELECT count(*) as count, meta(`subscriptions`).id AS id  FROM `subscriptions` WHERE firstName = 'Jack' AND meta(`subscriptions`).id NOT LIKE "_sync:%" GROUP BY meta(`subscriptions`).id`

**Comment by aBnormaLz** [comment]
Finally i had time to reproduce your bug. I fixed it with v 1.0.3 release, just modify the pom.xml, and it should be fine now :) I hope it's not too late.

**Comment by aBnormaLz** [comment]
I took a look at your changes, and i added the features you needed for the next release, feel free to use it

https://github.com/TeamWanari/couchbase-query-executor/tree/1.0.4
